management:
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: True

  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: observability-demo

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
